/**
 * 지역별 평균 순차감 트래킹를 위한 지역별 등급 및 평균 순차감 리스트 임시 추가 (21.11.29 Koo)
 * 11월 데이터로 업데이트 (21.12.03)
 */

type levelType = "상상" | "상중" | "상하" | "중상" | "중중" | "중하" | "하상" | "하중" | "하하";

export const areaLevels: { area: string; level: levelType }[] = [
  { area: '서울특별시송파구', level: '상상' },
  { area: '대구광역시서구', level: '하상' },
  { area: '서울특별시강동구', level: '상상' },
  { area: '서울특별시강남구', level: '상상' },
  { area: '서울특별시광진구', level: '상상' },
  { area: '서울특별시서초구', level: '상상' },
  { area: '전라남도장성군', level: '하상' },
  { area: '부산광역시중구', level: '하상' },
  { area: '인천광역시동구', level: '하상' },
  { area: '서울특별시노원구', level: '상상' },
  { area: '서울특별시중랑구', level: '상상' },
  { area: '대구광역시달서구', level: '중상' },
  { area: '부산광역시수영구', level: '중상' },
  { area: '경기도남양주시', level: '상상' },
  { area: '대구광역시중구', level: '하상' },
  { area: '경기도안양시동안구', level: '상상' },
  { area: '부산광역시사상구', level: '중상' },
  { area: '서울특별시성동구', level: '상상' },
  { area: '경기도고양시덕양구', level: '상상' },
  { area: '경기도고양시일산서구', level: '상상' },
  { area: '부산광역시해운대구', level: '상상' },
  { area: '경기도성남시분당구', level: '상상' },
  { area: '부산광역시북구', level: '중상' },
  { area: '경기도하남시', level: '상상' },
  { area: '경기도구리시', level: '중상' },
  { area: '부산광역시영도구', level: '하중' },
  { area: '경기도김포시', level: '상상' },
  { area: '서울특별시구로구', level: '상상' },
  { area: '대구광역시수성구', level: '중상' },
  { area: '경기도고양시일산동구', level: '상상' },
  { area: '경기도수원시영통구', level: '상상' },
  { area: '경상남도의령군', level: '하상' },
  { area: '경기도부천시', level: '상상' },
  { area: '부산광역시동구', level: '하상' },
  { area: '인천광역시미추홀구', level: '중상' },
  { area: '경기도수원시장안구', level: '중상' },
  { area: '부산광역시금정구', level: '중상' },
  { area: '서울특별시영등포구', level: '상중' },
  { area: '인천광역시부평구', level: '상상' },
  { area: '부산광역시기장군', level: '중상' },
  { area: '서울특별시양천구', level: '상중' },
  { area: '부산광역시연제구', level: '중상' },
  { area: '부산광역시동래구', level: '중상' },
  { area: '서울특별시동대문구', level: '상중' },
  { area: '경기도광명시', level: '중중' },
  { area: '부산광역시강서구', level: '중상' },
  { area: '서울특별시용산구', level: '중중' },
  { area: '대구광역시남구', level: '하중' },
  { area: '인천광역시서구', level: '상상' },
  { area: '부산광역시사하구', level: '중중' },
  { area: '경기도용인시수지구', level: '상상' },
  { area: '대구광역시북구', level: '중상' },
  { area: '서울특별시마포구', level: '상중' },
  { area: '경기도군포시', level: '중중' },
  { area: '서울특별시은평구', level: '상중' },
  { area: '경기도수원시권선구', level: '중상' },
  { area: '인천광역시남동구', level: '상상' },
  { area: '부산광역시남구', level: '중중' },
  { area: '광주광역시동구', level: '하중' },
  { area: '인천광역시연수구', level: '중상' },
  { area: '광주광역시서구', level: '하중' },
  { area: '경기도수원시팔달구', level: '하상' },
  { area: '서울특별시강북구', level: '상중' },
  { area: '경기도의정부시', level: '중상' },
  { area: '대구광역시동구', level: '중중' },
  { area: '광주광역시남구', level: '하중' },
  { area: '경기도여주시', level: '하중' },
  { area: '부산광역시부산진구', level: '중상' },
  { area: '서울특별시강서구', level: '상중' },
  { area: '전라북도정읍시', level: '하중' },
  { area: '경기도화성시', level: '상상' },
  { area: '경기도안양시만안구', level: '중중' },
  { area: '서울특별시성북구', level: '상중' },
  { area: '경기도시흥시', level: '상중' },
  { area: '인천광역시계양구', level: '중상' },
  { area: '경상남도창원시성산구', level: '중상' },
  { area: '경기도광주시', level: '상중' },
  { area: '인천광역시중구', level: '중중' },
  { area: '서울특별시도봉구', level: '중중' },
  { area: '전라북도완주군', level: '하중' },
  { area: '충청북도증평군', level: '하상' },
  { area: '충청북도진천군', level: '하중' },
  { area: '경기도파주시', level: '상중' },
  { area: '경상남도창원시진해구', level: '중상' },
  { area: '경기도양주시', level: '중중' },
  { area: '전라북도전주시완산구', level: '중상' },
  { area: '경상남도창원시마산합포구', level: '하상' },
  { area: '경상남도창원시의창구', level: '중상' },
  { area: '광주광역시광산구', level: '중중' },
  { area: '전라남도구례군', level: '하중' },
  { area: '충청북도영동군', level: '하하' },
  { area: '서울특별시동작구', level: '상중' },
  { area: '경기도오산시', level: '중중' },
  { area: '경상북도포항시남구', level: '하상' },
  { area: '대구광역시달성군', level: '중중' },
  { area: '경상북도포항시북구', level: '중상' },
  { area: '서울특별시금천구', level: '중하' },
  { area: '충청북도충주시', level: '중중' },
  { area: '충청북도괴산군', level: '하중' },
  { area: '경상북도김천시', level: '하중' },
  { area: '경기도의왕시', level: '중중' },
  { area: '경상남도창원시마산회원구', level: '하상' },
  { area: '전라북도남원시', level: '하중' },
  { area: '경기도동두천시', level: '하중' },
  { area: '광주광역시북구', level: '중중' },
  { area: '전라북도전주시덕진구', level: '중중' },
  { area: '경상남도김해시', level: '상상' },
  { area: '충청북도청주시상당구', level: '하상' },
  { area: '경기도평택시', level: '상중' },
  { area: '경상북도구미시', level: '중중' },
  { area: '경상북도칠곡군', level: '하중' },
  { area: '서울특별시중구', level: '중하' },
  { area: '제주특별자치도서귀포시', level: '하중' },
  { area: '충청북도청주시청원구', level: '중중' },
  { area: '전라북도익산시', level: '중중' },
  { area: '서울특별시관악구', level: '상하' },
  { area: '충청북도옥천군', level: '하하' },
  { area: '충청북도청주시서원구', level: '중중' },
  { area: '경기도용인시기흥구', level: '상하' },
  { area: '전라남도나주시', level: '하중' },
  { area: '전라북도김제시', level: '하중' },
  { area: '제주특별자치도제주시', level: '하상' },
  { area: '경상남도남해군', level: '하중' },
  { area: '경기도안산시상록구', level: '중하' },
  { area: '경기도포천시', level: '하중' },
  { area: '세종특별자치시', level: '상중' },
  { area: '경상북도영덕군', level: '하중' },
  { area: '경기도안산시단원구', level: '중중' },
  { area: '충청북도제천시', level: '하중' },
  { area: '대전광역시동구', level: '하하' },
  { area: '충청북도청주시흥덕구', level: '중중' },
  { area: '경상남도진주시', level: '중중' },
  { area: '강원도강릉시', level: '중중' },
  { area: '충청남도금산군', level: '하하' },
  { area: '충청남도아산시', level: '중중' },
  { area: '경기도가평군', level: '하하' },
  { area: '부산광역시서구', level: '하중' },
  { area: '강원도동해시', level: '하중' },
  { area: '전라북도군산시', level: '중중' },
  { area: '경기도과천시', level: '하하' },
  { area: '경상남도사천시', level: '하중' },
  { area: '경상남도거창군', level: '하중' },
  { area: '충청남도천안시서북구', level: '중중' },
  { area: '인천광역시강화군', level: '하하' },
  { area: '경상남도양산시', level: '중중' },
  { area: '충청북도음성군', level: '하중' },
  { area: '경상북도경주시', level: '중중' },
  { area: '강원도춘천시', level: '중중' },
  { area: '경기도성남시수정구', level: '중하' },
  { area: '전라남도광양시', level: '하하' },
  { area: '서울특별시종로구', level: '중하' },
  { area: '경기도이천시', level: '중하' },
  { area: '서울특별시서대문구', level: '상하' },
  { area: '대전광역시서구', level: '상하' },
  { area: '경기도성남시중원구', level: '중하' },
  { area: '경상북도경산시', level: '하중' },
  { area: '충청남도천안시동남구', level: '중하' },
  { area: '경상남도고성군', level: '하상' },
  { area: '강원도삼척시', level: '하중' },
  { area: '충청남도계룡시', level: '하하' },
  { area: '대전광역시중구', level: '중하' },
  { area: '충청남도서산시', level: '하하' },
  { area: '대전광역시유성구', level: '상하' },
  { area: '경상북도영천시', level: '하하' },
  { area: '경상남도창녕군', level: '하하' },
  { area: '강원도태백시', level: '하하' },
  { area: '대전광역시대덕구', level: '중하' },
  { area: '강원도홍천군', level: '하하' },
  { area: '강원도화천군', level: '하하' },
  { area: '경상북도울진군', level: '하하' },
  { area: '경상북도문경시', level: '하하' },
  { area: '강원도영월군', level: '하하' },
  { area: '강원도양양군', level: '하하' },
  { area: '전라북도부안군', level: '하하' },
  { area: '전라남도화순군', level: '하하' },
  { area: '전라남도담양군', level: '하하' },
  { area: '경상남도하동군', level: '하하' },
  { area: '강원도평창군', level: '하하' },
  { area: '강원도횡성군', level: '하하' },
  { area: '경상북도울릉군', level: '하하' },
  { area: '경기도안성시', level: '중하' },
  { area: '경상북도상주시', level: '하하' },
  { area: '충청북도보은군', level: '하하' },
  { area: '충청남도부여군', level: '하하' },
  { area: '경상북도고령군', level: '하하' },
  { area: '경기도연천군', level: '하하' },
  { area: '강원도철원군', level: '하하' },
  { area: '경상남도밀양시', level: '하하' },
  { area: '전라남도여수시', level: '중하' },
  { area: '전라남도순천시', level: '중하' },
  { area: '울산광역시남구', level: '중하' },
  { area: '충청남도논산시', level: '하하' },
  { area: '울산광역시중구', level: '하하' },
  { area: '경기도양평군', level: '하하' },
  { area: '울산광역시동구', level: '하하' },
  { area: '전라북도고창군', level: '하하' },
  { area: '충청남도예산군', level: '하하' },
  { area: '충청남도홍성군', level: '하하' },
  { area: '강원도인제군', level: '하하' },
  { area: '경기도용인시처인구', level: '중하' },
  { area: '울산광역시울주군', level: '하하' },
  { area: '전라남도고흥군', level: '하하' },
  { area: '울산광역시북구', level: '중하' },
  { area: '강원도원주시', level: '상하' },
  { area: '경상북도예천군', level: '하하' },
  { area: '경상북도영주시', level: '하하' },
  { area: '경상남도거제시', level: '중하' },
  { area: '경상남도통영시', level: '하하' },
  { area: '경상남도함안군', level: '하상' },
  { area: '강원도양구군', level: '하하' },
  { area: '충청남도당진시', level: '하하' },
  { area: '충청남도보령시', level: '하하' },
  { area: '전라남도목포시', level: '하하' },
  { area: '충청남도태안군', level: '하하' },
  { area: '경상북도안동시', level: '하하' },
  { area: '전라남도해남군', level: '하하' },
  { area: '강원도속초시', level: '하하' },
  { area: '전라남도무안군', level: '하하' },
  { area: '충청남도공주시', level: '하하' },
  { area: '전라남도함평군', level: '하하' },
  { area: '전라남도완도군', level: '하하' },
  { area: '전라남도영암군', level: '하하' },
  { area: '전라남도보성군', level: '하하' },
  { area: '경상북도청도군', level: '하하' },
  { area: '강원도고성군', level: '하하' },
  { area: '전라남도곡성군', level: '하하' },
  { area: '전라남도영광군', level: '하하' },
  { area: '전라북도순창군', level: '하하' },
  { area: '경상남도합천군', level: '하하' },
  { area: '충청북도단양군', level: '하하' },
  { area: '전라북도진안군', level: '하하' },
  { area: '경상북도의성군', level: '하하' },
  { area: '강원도정선군', level: '하하' },
  { area: '충청남도서천군', level: '하하' },
  { area: '전라남도강진군', level: '하하' },
  { area: '경상북도군위군', level: '하하' },
  { area: '전라북도무주군', level: '하하' },
  { area: '인천광역시옹진군', level: '하하' },
  { area: '전라북도임실군', level: '하하' },
  { area: '경상남도산청군', level: '하하' },
  { area: '전라북도장수군', level: '하하' },
  { area: '전라남도진도군', level: '하하' },
  { area: '경상남도함양군', level: '하하' },
  { area: '경상북도영양군', level: '하하' },
  { area: '경상북도청송군', level: '하하' },
  { area: '전라남도신안군', level: '하하' },
  { area: '충청남도청양군', level: '하하' },
  { area: '전라남도장흥군', level: '하하' },
  { area: '경상북도봉화군', level: '하하' },
  { area: '경상북도성주군', level: '하하' }
]

export const deductionPoints: any = {
  상상: 55764,
  상중: 46115,
  상하: 26459,
  중상: 51084,
  중중: 39831,
  중하: 24753,
  하상: 45105,
  하중: 38900,
  하하: 14466
}

export const getAreaLevel = (sido: string, gugun: string) => {
  let value = 0;
  const address = `${sido}${gugun}`.replace(/ /g, "");
  const targetArea = areaLevels.find((area) => area.area === address);

  if (targetArea) {
    value = deductionPoints[targetArea.level];
    return { ...targetArea, value };
  }
  return null;
};
